### PR TITLE
Add Changelog and GitHub Workflow

### PR DESCRIPTION
**Pull request by auggeeo**
:)
# 1.3.1
- Adds GitHub Workflow
- Adds a Changelog (changelog.md)
- Adds Android Geometry Dash Version in mod.json
- ~~Removes beta from Geode Version in mod.json (for when Geode updates to a new beta, the Geode mod (GDTweaks) will still function)~~ updated in 1.3.0
- Also I guess change W to a lowercase w in readme.md
- Also add your name and links to (what I think) your account id (is) in the game and shows your profile on click

### CODE REVIEW

**Comment by auggeeo** [comment]
here wait let me fix conflicts

**Comment by auggeeo** [comment]
there we go

**Comment by auggeeo** [comment]
let me do changelog things

**Comment by auggeeo** [comment]
@undefined06855 Can you please review my PR

**Comment by undefined06855** [comment]
damn this is good, thanks for this
edit: hold on a sec I need to mess around with my access tokens for the workflow

**Pull request merged**
