### PR TITLE
Split into individual files

### PR DESCRIPTION
**Pull request by auggeeo**
Split layers into individual files

### CODE REVIEW

**Comment by undefined06855** [comment]
OH MY GOD THANK YOU COOP SOMEONE ACTUALLY DID IT 
I'll look through this later though

**Comment by coopeeo** [comment]
lol

**Comment by auggeeo** [comment]
code is still messy but it's like organized into different files

**Review by undefined06855 — APPROVED** [review]
there's a few things but i might as well merge now, fix later

**Pull request merged**
